export type FormData = {
  invoiceNumber: string;
  invoiceDate: string;
  fullName: string;
  streetAndNumber: string;
  postalCode: string;
  locality: string;
  cityOrTown: string;
  country: string;
  vat: number;
  tin: string;
  clientFullName: string;
  clientAddress: string;
  clientPostalCode: string;
  clientLocality: string;
  clientCityOrTown: string;
  clientCountry: string;
  clientTin: string;
  currency: string;
  paymentDueDate: string;
  descriptionOfServices: string;
  services: {
    description: string;
    quantity: number;
    ratePerUnit: number;
    totalAmount: number;
  }[];
  paymentTerms: string;
  bankAccountDetails: string;
  paymentInstructions: string;
  termsAndConditions: string;
  shippingFees: number;
};
